### ISSUE TITLE
Rich HTML message not rendered: tablePart.body is not iterable at renderTable

### ISSUE THREAD

**Issue by bkil** [matrix-org/matrix-public-archive#237]
See the message immediately following this one:
* https://archive.matrix.org/r/matrix-therapy-group:matrix.org/date/2023/05/29?at=$OfDUSIFw69RwyR0rG2cYELpbUzl\_2OnFq8ev2JXbJbw
* 
```
Something went wrong…
tablePart.body is not iterable
This occurred while running at errorToDOM (/app/node_modules/hydrogen-view-sdk/lib-build/hydrogen.cjs.js:6746:17).

TypeError: tablePart.body is not iterable
    at renderTable (/app/node_modules/hydrogen-view-sdk/lib-build/hydrogen.cjs.js:10028:31)
    at table (/app/node_modules/hydrogen-view-sdk/lib-build/hydrogen.cjs.js:10038:26)
    at renderPart (/app/node_modules/hydrogen-view-sdk/lib-build/hydrogen.cjs.js:10054:10)
    at /app/node_modules/hydrogen-view-sdk/lib-build/hydrogen.cjs.js:9982:32
    at TemplateBuilder.mapSideEffect (/app/node_modules/hydrogen-view-sdk/lib-build/hydrogen.cjs.js:7228:5)
    at TextMessageView.renderMessageBody (/app/node_modules/hydrogen-view-sdk/lib-build/hydrogen.cjs.js:9977:7)
    at TextMessageView.render (/app/node_modules/hydrogen-view-sdk/lib-build/hydrogen.cjs.js:9829:28)
    at TextMessageView.mount (/app/node_modules/hydrogen-view-sdk/lib-build/hydrogen.cjs.js:6989:25)
    at mountView (/app/node_modules/hydrogen-view-sdk/lib-build/hydrogen.cjs.js:6738:17)
    at TilesListView.loadList (/app/node_modules/hydrogen-view-sdk/lib-build/hydrogen.cjs.js:6858:28)
```

**Comment by MadLittleMods** [comment]
Hey @bkil,

The Matrix Public Archive uses [Hydrogen](https://github.com/vector-im/hydrogen-web) under the hood and this is an upstream bug in Hydrogen itself. Since that project is in another GitHub org, I can't transfer the issue over there. Please [create an issue on that repo](https://github.com/vector-im/hydrogen-web/issues) with these details and perhaps the event content to reproduce.

**Comment by bkil** [comment]
Done https://github.com/vector-im/hydrogen-web/issues/1106
