### ISSUE TITLE
Searching for a Null Byte Triggers a Server Error

### ISSUE THREAD

**Issue by davidegirardi** [matrix-org/matrix-public-archive#80]
Visiting this URL triggers a 500: `/?search=%00`

It _could_ be an issue in `node-fetch` but I am not familiar enough with the code to be sure.

**Comment by MadLittleMods** [comment]
@davidegirardi I've updated the error message to be a bit more understandable: https://github.com/matrix-org/matrix-public-archive/pull/84

But you should also raise this in the Synapse issue tracker since that input to `/_matrix/client/v3/publicRooms`  causes a 500 error:

```
2022-10-18 03:55:45,082 - synapse.http.server - 123 - ERROR - POST-51351 - Failed handle request via 'PublicRoomListRestServlet': <XForwardedForRequest at 0x10f50d4c0 method='POST' uri='/_matrix/client/v3/publicRooms?' clientproto='HTTP/1.1' site='8008'>
Traceback (most recent call last):
  File "synapse/synapse/http/server.py", line 306, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "synapse/synapse/http/server.py", line 512, in _async_render
    callback_return = await raw_callback_return
  File "synapse/synapse/rest/client/room.py", line 544, in on_POST
    data = await handler.get_local_public_room_list(
  File "synapse/synapse/handlers/room_list.py", line 103, in get_local_public_room_list
    return await self._get_public_room_list(
  File "synapse/synapse/handlers/room_list.py", line 164, in _get_public_room_list
    results = await self.store.get_largest_public_rooms(
  File "synapse/synapse/storage/databases/main/room.py", line 472, in get_largest_public_rooms
    ret_val = await self.db_pool.runInteraction(
  File "synapse/synapse/storage/database.py", line 881, in runInteraction
    return await delay_cancellation(_runInteraction())
  File "synapse/.venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "synapse/.venv/lib/python3.9/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "synapse/synapse/storage/database.py", line 848, in _runInteraction
    result = await self.runWithConnection(
  File "synapse/synapse/storage/database.py", line 976, in runWithConnection
    return await make_deferred_yieldable(
  File "synapse/.venv/lib/python3.9/site-packages/twisted/python/threadpool.py", line 244, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
  File "synapse/.venv/lib/python3.9/site-packages/twisted/python/threadpool.py", line 260, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
  File "synapse/.venv/lib/python3.9/site-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "synapse/.venv/lib/python3.9/site-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
  File "synapse/.venv/lib/python3.9/site-packages/twisted/enterprise/adbapi.py", line 282, in _runWithConnection
    result = func(conn, *args, **kw)
  File "synapse/synapse/storage/database.py", line 969, in inner_func
    return func(db_conn, *args, **kwargs)
  File "synapse/synapse/storage/database.py", line 710, in new_transaction
    r = func(cursor, *args, **kwargs)
  File "synapse/synapse/storage/databases/main/room.py", line 463, in _get_largest_public_rooms_txn
    txn.execute(sql, query_args)
  File "synapse/synapse/storage/database.py", line 388, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "synapse/synapse/storage/database.py", line 436, in _do_execute
    return func(sql, *args, **kwargs)
ValueError: A string literal cannot contain NUL (0x00) characters.
````

**Comment by davidegirardi** [comment]
[Done](https://github.com/matrix-org/synapse/issues/14223).
